### ISSUE TITLE
duping issue with hidden blade

### ISSUE THREAD

**Issue by maccoggs** [BaiterYamato/Assassins-Craft-Chronicles#1]
if you hold out the hidden blade in your offhand (shield hand) and right click to extend it, it will dupe into your main hand extended while the closed one remains in your offhand.

**Comment by BaiterYamato** [comment]
Thanks for the feedback, it motivated me to continue with the mod, the bug was fixed by your feedback, I'll just finish the recipe items and release the update as soon as possible

**Comment by maccoggs** [comment]
don't give up bro, I'm running it on a server I just started with a few friends of mine keep going man we love the mod!
